# Исключения

![image](https://raw.githubusercontent.com/ait-tr/cohort25/main/basic_programming/lesson_46/img/1.png)

* `ArithmeticException` - исключение, возникающее при неправильных арифметических операциях (потомок `RuntimeException`)
* `NullPointerException` - исключение, возникающее при работе с переменной, которая не указывает на объект (потомок `RuntimeException`)
* `ArrayIndexOutOfBoundsException` - исключение, возникающее при выходе за границы массива (потомок `IndexOutOfBoundsException`)
* `OutOfMemoryError` - исключение, возникающее при переполнении памяти (потомок `VirtualMachineError`)
* `FileNotFoundException` - исключение, возникающее при обращении к несуществующему файлу (потомок `IOException`)

* `Throwable` - предок всех исключений. Содержит поля и методы, которые свойственны всем исключениям

```
class Throwable {
    private String detailMessage; // содержит более детальную информацию об ошибке
    
    private StackTraceElement[] stackTrace; // последовательность вызовов, которая привела к ошибке
```

* `Error` - системные ошибки, связанные с железом или с операционной системой (переполнение памяти, стека вызовов, глобальная ошибка ввода вывода).
* `Exception` - ошибки, возникающие при работе программы и неаккуратном ее использовании

### Перехват исключений

* В блоке `try` указываем код, в котором может возникнуть исключение
* В блоке `catch` указываем тип исключения, который следует перехватить и среагировать

### Выброс исключений

* Вы можете сами выбрасывать исключения с помощью оператора `throw`
* Можно сделать свой класс исключений с помощью наследования (всегда от `RuntimeException`)

### Проверяемые исключения (checked exceptions)

* `Throwable`, `Exception` и его потомки, кроме `RuntimeException` 
* Если метод выбрасывает проверяемое исключение, то он обязан об этом сообщить через `throws`:

```
private void ensureOpen() throws IOException {
    if (in == null)
        throw new IOException("Stream closed");
}
```

* Таким образом, вы явно говорите о том, что ваш метод может выбросить исключение.
* Проверяемые исключения придумали для того, чтобы заставить вас их проверять
* Почему `throws` - это плохо - потому что вы светите ошибками в верхних частях программы.
* Например, у вас не работает база данных, а вы пользователю на сайте показали, где она у вас находится, какой к ней пароль и т/д
* Лучше - обрабатывать ошибки там, где они возникают, а не доводить их до конечного пользователя, ему нужно видеть ограниченную информацию.

### Словарик

* `Throwable` - выбрасываемый
* `Exception` - исключение
* `RuntimeException` - исключение, возникающее во время выполнения программы
* `try` - попытаться
* `catch` - поймать

